### ISSUE TITLE
Register's callback is no longer supported

### ISSUE THREAD

**Issue by delvedor** [carlozamagni/fastify-google-cloud-storage#2]
You have declared a callback for the `register` API, which will never we called since it is no longer supported.

https://github.com/carlozamagni/fastify-google-cloud-storage/blob/19ce1b75da642c899f304f0faf03ed6e68cd9e60/test.js#L17-L19

I also suggest you add another test to verify the behavior of the plugin if the following snippet throws an error:
https://github.com/carlozamagni/fastify-google-cloud-storage/blob/19ce1b75da642c899f304f0faf03ed6e68cd9e60/index.js#L14-L15

**Comment by carlozamagni** [comment]
Hi @delvedor, i just removed the callback on the register API, but i'm having trouble on writing the test you suggested. I checked both the documentation and the source code for Cloud Storage api and seems to me that in no way the creation of an instance of Storage could throw an error since it's just a proxy with default parameters set on creation.
I'm thinking about removing the try - catch block, do you have a better suggestion?

Thank you.

**Comment by delvedor** [comment]
Hello! Following is type definitions of the storage options:
```ts
export interface StorageOptions extends GoogleAuthOptions {
  autoRetry?: boolean;
  maxRetries?: number;
  promise?: typeof Promise;
}
```

Have you tried to pass something wrong? `promise: 42` for example.

**Comment by carlozamagni** [comment]
I did;
i first tried passing plainly wrong parameters, then i followed your suggestion about the promise, but the client doesn't seems to care (at least at creation time, of course it throws errors when you try to access actual resources).

Since i'm limiting the options passed to the `Storage` object to the `projectId`and `keyFilename` parameters i tried to tamper them by passing unexpected values, but again, no way.

**Comment by delvedor** [comment]
Lol, luckily types will save the world! (sigh...)
I guess you can close this issue, the code is simple enough, and it should always work :)

**Comment by carlozamagni** [comment]
Man, I completely agree with You about the types :)

I think i'll end up performing a list of the buckets immediately after the creation of the Storage object just to validate the configuration (according to the issue Matteo opened yesterday #4 ); i don't like the approach very very much but at the moment is the only way i can think of to avoid having an "unvalid" proxy.
